behaviors:
  Survivor:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.3
        demo_path: Demo\SurvivorDemo.demo
    behavioral_cloning:
      strength: 0.3
      demo_path: Demo\SurvivorDemo.demo
    max_steps: 500000000
    time_horizon: 2056
    summary_freq: 10000